//! site — the GUI's pages, EMBEDDED in the binary.
//!
//! Orpheus's `.lat` libraries have always been `include_str!`-embedded, so the language
//! and every tool travel inside the executable. The web GUI was the one exception: it
//! read `lib/site/*` from disk. That is fine on a workstation and impossible on Android,
//! where an app's executable is extracted from the APK into `nativeLibraryDir` and there
//! is no repository checkout beside it.
//!
//! So the site travels too. `serve` prefers a real `--root` directory when one exists
//! (so editing a page and reloading still works during development); when the directory
//! is absent, these embedded copies answer instead — the single-binary path a phone
//! needs. Text pages are `include_str!`, the three webfonts `include_bytes!`.
//!
//! Generated by hand from `lib/site/` — the list is short and stable; a build script
//! would add a dependency-free-ness caveat for no real gain.

/// One embedded file: path relative to the site root, and its bytes.
pub struct Asset {
    pub path: &'static str,
    pub bytes: &'static [u8],
}

/// Every page and font of the GUI.
pub const ASSETS: &[Asset] = &[
    Asset { path: "board.facet", bytes: include_bytes!("../lib/site/board.facet") },
    Asset { path: "chart.html", bytes: include_bytes!("../lib/site/chart.html") },
    Asset { path: "chess.html", bytes: include_bytes!("../lib/site/chess.html") },
    Asset { path: "compile.html", bytes: include_bytes!("../lib/site/compile.html") },
    Asset { path: "derive.html", bytes: include_bytes!("../lib/site/derive.html") },
    Asset { path: "docs.html", bytes: include_bytes!("../lib/site/docs.html") },
    Asset { path: "draw.html", bytes: include_bytes!("../lib/site/draw.html") },
    Asset { path: "editor.html", bytes: include_bytes!("../lib/site/editor.html") },
    Asset { path: "fin.html", bytes: include_bytes!("../lib/site/fin.html") },
    Asset { path: "fonts/ligos-bold.woff2", bytes: include_bytes!("../lib/site/fonts/ligos-bold.woff2") },
    Asset { path: "fonts/ligos-italic.woff2", bytes: include_bytes!("../lib/site/fonts/ligos-italic.woff2") },
    Asset { path: "fonts/ligos-regular.woff2", bytes: include_bytes!("../lib/site/fonts/ligos-regular.woff2") },
    Asset { path: "gpu.html", bytes: include_bytes!("../lib/site/gpu.html") },
    Asset { path: "grammar.html", bytes: include_bytes!("../lib/site/grammar.html") },
    Asset { path: "index.facet", bytes: include_bytes!("../lib/site/index.facet") },
    Asset { path: "learn.facet", bytes: include_bytes!("../lib/site/learn.facet") },
    Asset { path: "ligurian-grammar.md", bytes: include_bytes!("../lib/site/ligurian-grammar.md") },
    Asset { path: "network.facet", bytes: include_bytes!("../lib/site/network.facet") },
    Asset { path: "notes.html", bytes: include_bytes!("../lib/site/notes.html") },
    Asset { path: "phono.html", bytes: include_bytes!("../lib/site/phono.html") },
    Asset { path: "plan.html", bytes: include_bytes!("../lib/site/plan.html") },
    Asset { path: "soundlib.html", bytes: include_bytes!("../lib/site/soundlib.html") },
    Asset { path: "system.html", bytes: include_bytes!("../lib/site/system.html") },
    Asset { path: "tools.facet", bytes: include_bytes!("../lib/site/tools.facet") },
    Asset { path: "trade.html", bytes: include_bytes!("../lib/site/trade.html") },
    Asset { path: "xiangqi.html", bytes: include_bytes!("../lib/site/xiangqi.html") },
];

/// Look up an embedded asset by its site-relative path (no leading slash).
pub fn get(path: &str) -> Option<&'static [u8]> {
    ASSETS.iter().find(|a| a.path == path).map(|a| a.bytes)
}

/// Is this build carrying the site? (Always true; kept as the honest predicate the
/// server asks before reporting "serving embedded pages".)
pub fn available() -> bool {
    !ASSETS.is_empty()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_whole_gui_is_embedded() {
        // the pages the GUI cannot start without
        for p in ["index.facet", "system.html", "tools.facet", "trade.html", "network.facet"] {
            assert!(get(p).is_some(), "missing embedded asset: {}", p);
        }
        assert!(available());
    }

    #[test]
    fn fonts_are_embedded_as_bytes() {
        let f = get("fonts/ligos-regular.woff2").expect("regular font");
        assert!(f.len() > 10_000, "font looks truncated");
        assert_eq!(&f[..4], b"wOF2", "WOFF2 magic survives embedding");
    }

    #[test]
    fn embedded_matches_the_repository_when_present() {
        // when the checkout is beside us (the dev case), every embedded byte must equal
        // the file on disk — otherwise the phone would serve a stale GUI
        for a in ASSETS {
            let p = std::path::Path::new("lib/site").join(a.path);
            if let Ok(disk) = std::fs::read(&p) {
                assert_eq!(disk, a.bytes, "embedded copy of {} is stale", a.path);
            }
        }
    }
}
